### ISSUE TITLE
Fails on redux-form 7.3.0

### ISSUE THREAD

**Issue by Pouja** [42BV/jarb-redux-form#6]
![2017-09-11-22 01 20_1365x252_scrot](https://user-images.githubusercontent.com/2385144/30294149-68d64b18-973c-11e7-8f27-fd4847605b3e.png)

I know that it works with 6.5.0, just wanted to give you the heads up that it will probably break at 7.x.x

**Comment by MrHus** [comment]
Long time overdue, but this should be fixed with: https://github.com/42BV/jarb-redux-form/pull/7.
